name: build

on: push

jobs:
  grade:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "/home/runner/.pyenv/bin" >> $GITHUB_PATH
          echo "/home/runner/.local/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Set up grading environment
        run: |
          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          pyenv install 3.6.3
          echo "eval '$(pyenv init -)'" >> ~/.bashrc
          eval "$(pyenv virtualenv-init -)" >> ~/.bashrc
          source ~/.bashrc
          pyenv global 3.6.3
          pip install --upgrade pip
          pip install pipenv
          pip install coverage
      - name: Lint with flake8
        run: |
          pipenv install --dev
          pipenv run flake8 src
          pipenv run flake8 tests
        #continue-on-error: true
      - name: Lint with pylint
        run: |
          pipenv run pylint src
          pipenv run pylint tests
        #continue-on-error: true
      - name: Check pydocstyle
        run: |
          pipenv run pydocstyle
      - name: Run program
        run: |
          pipenv run python3 src/connect4.py
        #continue-on-error: true
      - name: Run testing
        run: |
          pipenv install pytest
          pipenv run pytest -s --cov-config .coveragerc --cov-report term-missing --cov-report xml --cov --cov-branch
        #continue-on-error: true
        if: always()
        env:
          PIPENV_VENV_IN_PROJECT: 1
          PIPENV_IGNORE_VIRTUALENVS: 1
